### ISSUE TITLE
丢失 response 的原始 header 头

### ISSUE THREAD

**Issue by isecret** [flc1125/laravel-middleware-cache-response#1]
使用包的时候发现会丢掉原始 response 的 header 头，因为是接口项目，部分接口需要缓存一段时间，但是发现 header 头被重置为 `text/html`。

**Comment by flc1125** [comment]
对的，因为目前还不支持 `header` 头的缓存。`header` 头的情况比较特殊，属于某个时间点和状态性的数据。此类数据不建议缓存。就好比静态页面下，登录状态均采用前端方式去展示。

说个简单的例子，如加上 `header` 的缓存你感受下：

A用户登录访问后生成缓存，此时数据内缓存的是A用户的cookie。如果此时有B、C等用户访问，其实间接性就是登录了A用户，进行访问。在安全上有漏洞。

> 缓存中间件建议用在纯静态页面或可静态（如新闻详细页）的页面

**Comment by isecret** [comment]
嗯，这样讲很有道理，看来我需要将缓存单独存放。
