### ISSUE TITLE
应该加一个APP_DEBUG判断

### ISSUE THREAD

**Issue by anerg2046** [flc1125/laravel-middleware-cache-response#2]
开发环境不应该实际缓存

**Comment by flc1125** [comment]
好主意，尽快实现

**Comment by flc1125** [comment]
仔细想了下，**觉得还是不考虑增加开发环境不缓存。** 原因如下：

> 如 Laravel 自带的 Cache 机制，不会因为当前环境是dev或debug等因素而忽略缓存。

**Comment by anerg2046** [comment]
在你这个基础上我抽空完善了下，可以参考
https://github.com/anerg2046/laravel-cache-page
不依赖debug环境，而是配置参数了

因为如果调整页面的时候，缓存很烦
